platform:
    - x64

cache:
    - C:\Users\appveyor\.opam

install:
    - npm install
    - npm install -g rimraf
    - powershell ./setup-esy.ps1

build_script:
    # Reset %PATH% to avoid cygwin DLL conflicts with cause
    # *** fatal error - cygheap base mismatch detected
    - echo $PATH
    - set PATH=C:\Windows\System32;C:\Program Files\Git\cmd;C:\Windows;C:\Program Files (x86)\nodejs;C:\Users\appveyor\AppData\Roaming\npm;C:\projects\esy\node_modules\esy-bash\.cygwin\bin;C:\Program Files\AppVeyor\BuildAgent;C:\Windows\System32\WindowsPowerShell\v1.0;
    - powershell ./build-esy.ps1

test_script:
    # Once we're done building, we need to REMOVE the `.bash_profile` -> it will initialize OPAM which will conflict
    # with esy's isolated environment
    - rimraf C:/Users/appveyor/.bash_profile
    - set ESY=C:/projects/esy/_release/_build/default/esy/bin/esyCommand.exe
    - set HOME=C:/Users/appveyor
    - echo $ESY
    - node test.js

on_finish:
      - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
